kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64


steps:
  - name: go build
    environment:
      APP_NAME: fhgo
    commands:
      - echo $${0}
      - export GOROOT=/usr/local/go
      - export GOPATH=/data/gopackage
      - export GOBIN=$GOROOT/bin
      - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
      - export GOPROXY=https://goproxy.cn
      - cd server
      - go mod tidy
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

  - name: image build
    environment:
      APP_NAME: fhgo
    commands:
      - pwd
      - docker build -t $APP_NAME:latest .

  - name: docker run
    environment:
      APP_NAME: fhgo
    commands:
      - pwd
      - echo `docker stop $APP_NAME`
      - echo `docker rm $APP_NAME`
      - docker image prune -f
      - docker run -d --name  $APP_NAME   -p 18080:8080 -p 16060:6060  $APP_NAME
trigger:
  branch:
    - master