FHGo:
  Port: 8974
  Pprof:
    Enabled: true
    Port: 6060
Redis:
  Host: 127.0.0.1
  Port: 6379
  UserName: admin
  Password: admin
MySQL:
  Host: 127.0.0.1
  Port: 3306
  UserName: admin
  Password: admin